### ISSUE TITLE
Incorrect result for surface integration in 1d

### ISSUE THREAD

**Issue by lxvm** [maltezfaria/ImplicitIntegration.jl#16]
Hello,

Thank you for the very nice package. I was writing a package extension in [AutoBZCore.jl](https://github.com/lxvm/AutoBZCore.jl/pull/14) and I noticed that 1d surface integration below doesn't return the correct result.

Since in AutoBZCore.jl I was using the package to compute DOS of simple tight-binding models, I'll take the example $\int_0^1 dk \delta(E-cos(2\pi k)) = 1/\pi\sqrt{1-E^2}$ for $|E|<1$ and zero otherwise.
```jl
julia> using ImplicitIntegration

julia> function dos_integer_1d_exact(E::Real, t=oneunit(E))
           x = abs(E/2t)
           if x <= 1
               1/sqrt(1 - x^2)/(pi*2t)
           else
               zero(inv(oneunit(t)))
           end
       end
dos_integer_1d_exact (generic function with 2 methods)

julia> ω = 0.1
0.1

julia> dos_integer_1d_exact(ω, 0.5)
0.31991347258556546

julia> result = integrate(x -> 1/sqrt(sinpi(2x[1])^2), x -> cospi(2x[1]) - ω, (0.0,), (1.0,); surface = true, tol=1e-2)
(val = 0.0, logger = LogInfo:
|- Subdivisions:
|-- Dimension 1: 0 subdivisions
)
```
Here the solution is incorrectly returned as zero. However, the package works brilliantly for higher dimensions, e.g. in 2d 
```jl
julia> using Elliptic

julia> function dos_integer_2d_exact(E::Real, t=oneunit(E))
           x = abs(E/4t)
           if x <= 1
               # note Elliptic and SpecialFunctions accept the elliptic modulus m = k^2
               1/(pi^2*2t)*Elliptic.K(1 - x^2)
           else
               zero(inv(oneunit(t)))
           end
       end
dos_integer_2d_exact (generic function with 2 methods)

julia> dos_integer_2d_exact(ω, 0.5)
0.4442065815373786

julia> result = integrate(x -> 1/sqrt(sinpi(2x[1])^2+sinpi(2x[2])^2)/2pi, x -> cospi(2x[1]) + cospi(2x[2]) - 0.1, (0.0,0.0), (1.0,1.0); surface = true, tol=1e-2)
(val = 0.444207969139339, logger = LogInfo:
|- Subdivisions:
|-- Dimension 1: 32 subdivisions
|-- Dimension 2: 47 subdivisions
)
```
I know the novelty of this package is in the higher-dimensional methods, but if getting the one-dimensional case to work is possible I think that would round out the package very nicely. Thanks.

**Comment by maltezfaria** [comment]
Thanks for raising the issue: this was indeed a corner case. 

I have pushed a patch to `main` (see [7cab7cd](https://github.com/maltezfaria/ImplicitIntegration.jl/commit/7cab7cd4c8f6449bd78eabb9a0e8f70b43236c6a)). Let me know if that does not work.

*Note*: I think there was a typo with your $1 / |\nabla \phi|$ missing a factor of $2\pi$.

**Comment by lxvm** [comment]
Yes, thanks, I can confirm the fix works! Yes, there is a typo in my 1d example.

**Comment by maltezfaria** [comment]
Great. I tagged `v0.1.1` with the fix.
