### ISSUE TITLE
Design an interface to make `integrate` and `quadgaen` work on user-defined custom types

### ISSUE THREAD

**Issue by antoine-levitt** [maltezfaria/ImplicitIntegration.jl#6]
Support a way for the user to input custom restriction to axes. I'm not 100% sure how to do that. In particular restriction_type is annoying (because my type has functions in its type parameters, and in some cases the type might depend on along which axis it's restricted), is it feasible to get rid of it?

**Comment by maltezfaria** [comment]
Let me think about how to expose `restriction` to make it part of the interface. It should be doable, I need a bit of time to look at the code and propose a solution.

**Comment by maltezfaria** [comment]
Maybe we should use this issue to discuss a reasonable *interface* instead of the more specific issue with `restriction`?

**Comment by antoine-levitt** [comment]
One thing I thought was to have a single phi(x) method, which is called with intervals, duals and intervals of duals, instead of having separate functions. This is equally easy to overload (it's not completely trivial to figure out the how the dual stuff works but you just have to copy/paste it from somewhere), works outside the box with no effort if you don't want to customize anything, and has no additional API surface. For relatively complex functions, it also allows a workflow where you only overload the parts you need and let intervalarithmetic / forwarddiff do the job for you if you don't care. You do have to depend on ForwardDiff and IntervalArithmetic but these are two pretty standard and stable packages so I'd say it's fine.

For restrict, simply have a default `restrict(phi, val, dim) = (x -> phi(...))`, which again can be overloaded?

**Comment by maltezfaria** [comment]
Interface proposal:

Suppose `phi` takes `R^N` --> `R`. Then the following interface could work:

- `phi(x::SVector{N,<:Real})` --> eval
- `phi(I::SVector{N,<:Interval})` --> bound
- `phi(x::SVector{N,<:ForwardDiff.Dual{Tg,T<:Real,M}})`, `M <= N` --> eval Jacobian vector product
- `phi(x::SVector{N,<:ForwardDiff.Dual{Tg,T<:Interval,M}})`, `M <= N` --> bound Jacobian vector product

**Comment by maltezfaria** [comment]
@antoine-levitt I added some documentation [here](https://maltezfaria.github.io/ImplicitIntegration.jl/dev/#Interface-methods). Would you mind taking a look and letting me know what you think? Feel free to patch it as you see fit.

**Comment by maltezfaria** [comment]
I think we can consider this done right? Closing it...
